### ISSUE TITLE
Add intro sentence for 02-common-mistakes.md

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#102]
The very first chunk of text in 02-common-mistakes.md is a list of common spreadsheet errors. Would be good to have a sentence or two of introduction here.

**Comment by anelda** [comment]
Working on this one - suggesting a sentence, please fix language and change if this isn't what you had in mind? Will submit PR now

**Comment by anelda** [comment]
Oops, combined it with another commit for one of the other issues - #140 
@ErinBecker  Please let me know if you need me to revert?

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/140. Thanks @anelda
