### ISSUE TITLE
Documentation on how to freeze column headers goes to Excel 2016 documentation

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#104]
But earlier we prompted the learners to install LibreOffice. We should either include both sets of documentation or only that for LibreOffice. 

Here's a link to LibreOffice freeze row/column instructions: https://help.libreoffice.org/Calc/Freezing_Rows_or_Columns_as_Headers

I haven't tested these instructions.

**Comment by zjsteyn** [comment]
Will work on this during BBQ, 
1. I'll Test instructions
2. Provide additional links to instructions

**Comment by ErinBecker** [comment]
From conversations with instructors, it appears that most learners and instructors are teaching this with Excel only. Given that, I rescind my comments here. We can just focus on Excel examples.
