### ISSUE TITLE
Add solutions for exercises

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#113]
Are these already somewhere? Is there any reason not to have them in the rendered lesson pages?

**Comment by zjsteyn** [comment]
To consider - Pull request for Data as dates exersize #129

**Comment by ErinBecker** [comment]
Also this PR https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/162

**Comment by ErinBecker** [comment]
Two exercises still missing solutions:

- 01-format-data first exercise - add "solution" noting that the next module is a detailed solution to this exercise.

- 04-quality-control - first exercise - fix data link (as discussed in https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/163)
- 04-quality-control - second exercise - add solution based on data file that @zjsteyn put together for the previous exercise

**Comment by tracykteal** [comment]
Addressed 01 exercise in https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/179
