### ISSUE TITLE
Using Excel instead of LibreOffice for examples

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#117]
In many places the spreadsheets lessons use Excel to demonstrate errors and functions. I don't have any problem with Excel, but I'm worried that these may not translate directly into the learner's environment if they're using LibreOffice (or some other software). For example in 04-quality-control.md under "Quality Assurance" the screenshots are all for Excel, even though LibreOffice is mentioned directly above the screenshots as another example where you could perform data validation. I'm worried that an instructor who has learners using LibreOffice won't be able to translate these steps to the appropriate steps for LibreOffice off the cuff.

Should we add LibreOffice equivalents in all the places where Excel is used? What is the distribution of software used by learners who attend this workshop?

**Comment by zjsteyn** [comment]
If a user is using Linux they can't easily run MS Office on their machine, then the Excel only examples are a bit limited, one could at least consider adding links to relevant Libre office documentation.

Will be able to provide links during the BBQ

**Comment by ErinBecker** [comment]
From conversations with instructors, it appears that most learners and instructors are teaching this with Excel only. Given that, I rescind my comments here. We can just focus on Excel examples.
