### ISSUE TITLE
Add sample files to the data repository

### ISSUE THREAD

**Issue by apawlik** [datacarpentry/spreadsheet-ecology-lesson#15]
Some of the small sample files with mistakes in Excel (available via previous commits when the data was still stored in the repo) could be now moved to the data repository. However, these are not ecology specific. Also, since there is now a messy dataset available, maybe these are not needed?

**Comment by ErinBecker** [comment]
@apawlik With the messy dataset, I think maybe this is no longer needed. Ok to close?

**Comment by ErinBecker** [comment]
@apawlik - I'm closing this as it seems that this is no longer relevant given the new dataset structure. Please let me know if this needs to be reopened.
