### ISSUE TITLE
Merge 'manage-date-time.md' with dates-as-data

### ISSUE THREAD

**Issue by apawlik** [datacarpentry/spreadsheet-ecology-lesson#16]
merge the contents of https://github.com/datacarpentry/excel-ecology/blob/gh-pages/manage-date-time.md with https://github.com/datacarpentry/excel-ecology/blob/gh-pages/03-dates-as-data.md
And add @acorpuz to the list of contributors.

**Comment by alex-konovalov** [comment]
@apawlik I would like to work on this issue to complete my instructor training - will submit a PR shortly.

**Comment by alex-konovalov** [comment]
@apawlik done - please see #56.
