### ISSUE TITLE
remove data/biology directory

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#167]
@tracykteal should we remove the data/biology directory? There are a lot of data files in here, but the official files are on figshare now so I think having this directory is confusing. If we're going to keep it, we should explain somewhere how to use these additional datasets.

**Comment by tracykteal** [comment]
I agree it's more confusing than useful, and we should remove it. It's easy enough to download all the files from Figshare, even if you've cloned the repo and are working on the lessons locally, and then we also don't need to worry about keeping data files in synch.
