### ISSUE TITLE
Cheat sheet for the messy data

### ISSUE THREAD

**Issue by apawlik** [datacarpentry/spreadsheet-ecology-lesson#17]
A cheatsheet/list of issues with the messy data would be useful for instructors to have.

**Comment by tracykteal** [comment]
Is this covered with the new layout in http://datacarpentry.github.io/spreadsheet-ecology-lesson/02-common-mistakes.html and the instructors notes? Or do we need something more?

**Comment by apawlik** [comment]
This looks comprehensive. Just in case (if we missed anything), notes that participants made in 2 workshops:
[Utrecht](https://datacarpentry.etherpad.mozilla.org/68) from line 53
[Ljubljana](https://datacarpentry.etherpad.mozilla.org/2015-07-20-ljubljana?) - from line 27

**Comment by ErinBecker** [comment]
Thanks @apawlik. Closing with 02-common-mistakes.
