### ISSUE TITLE
The hyperlinks between parts of the course are broken

### ISSUE THREAD

**Issue by nicoguaro** [datacarpentry/spreadsheet-ecology-lesson#19]
Take for example the [introduction](https://github.com/datacarpentry/excel-ecology/blob/gh-pages/00-intro.md), that links to the topic
1. [Formatting data tables in spreadsheets.](https://github.com/datacarpentry/excel-ecology/blob/gh-pages/01-format-data.html)

That is not right, it should point to [this](https://github.com/datacarpentry/excel-ecology/blob/gh-pages/01-format-data.md).

The same happens with ``.csv`` files, and other links.

**Comment by tracykteal** [comment]
@nicoguaro thanks for pointing this out, and I think this is fixed. 

Can you take a look at http://datacarpentry.github.io/spreadsheet-ecology-lesson/ to check?

**Comment by nicoguaro** [comment]
It is working now. I'm glad that you corrected it.

**Comment by tracykteal** [comment]
Great, thanks for filing. Closing issue.
