### ISSUE TITLE
link to data for sorting exercise 404's

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#191]
The first Exercise in http://www.datacarpentry.org/spreadsheet-ecology-lesson/04-quality-control/ has this link for the dataset: https://github.com/datacarpentry/spreadsheet-ecology-lesson/blob/gh-pages/data/survey_data_messy_quality_control.xlsx?raw=true but it 404s.

**Comment by ErinBecker** [comment]
The link now goes to the correct page, but doesn't automatically download the data. @tracykteal - could you remind me how to get the data to download automatically?

**Comment by primerano** [comment]
I mentioned it on your commit too but it looks like the file was recently renamed.  

New URL is https://github.com/datacarpentry/spreadsheet-ecology-lesson/blob/gh-pages/data/survey_data_spreadsheet_messy.xls?raw=true
