### ISSUE TITLE
AS used before it is taught

### ISSUE THREAD

**Issue by AlfAWolf140** [datacarpentry/spreadsheet-ecology-lesson#193]
When I was teaching the lesson earlier I noticed that AS is used in the IFNULL and NULLIF sections before it's taught in the ALIAS section. This meant that I ended up explaining it twice. I don't know which would be the better option, but I'd like to suggest either:

a) Remove the AS statements from the following
SELECT species_id, plot_id, NULLIF(plot_id, 7) AS partial_plot_id
FROM surveys;

SELECT species_id, sex, IFNULL(sex, 'U') AS non_null_sex
FROM surveys;

b) Move the alias section above the IFNULL and NULLIF sections

**Comment by tracykteal** [comment]
Thanks @AlfAWolf140. Is this comment related to the [SQL lesson](https://github.com/datacarpentry/sql-ecology-lesson) rather than the spreadsheet one?

**Comment by AlfAWolf140** [comment]
Ah sorry - did I end up putting it in the wrong section? Yes it should be
related to SQL lesson.

**Comment by AlfAWolf140** [comment]
Move to correct place.
