### ISSUE TITLE
Revised Learning Objectives for "Data Organization in Spreadsheets"

### ISSUE THREAD

**Issue by mcnabbkb** [datacarpentry/spreadsheet-ecology-lesson#197]
After reading through the Ecology Workshop, I thought these learning objectives from "Data Organization in Spreadsheets" could be revised and improved.

After this lesson, you will be able to:
•	Model good data entry practices - formatting data tables in spreadsheets
•	Identify and address common formatting mistakes
•	Compare approaches for handling dates in spreadsheets
•	Prepare spreadsheets using basic quality control and data manipulation principles
•	Demonstrate methods for exporting data from spreadsheets using applications like R

This is my contribution for my instructor training.

**Comment by amandawhitmire** [comment]
I'm looking through issues for my instructor training, and I just wanted to second these recommendations. The wording change to what someone will be able to DO (identify, compare, etc.) is better practice than the current "you will learn...." framing. Just my $0.02. 

Who decides whether or not to make these changes and then close the issue? I'm not going to submit my comment as any sort of task toward checkout, but I'm curious about how this process works.

**Comment by hoytpr** [comment]
Would @mcnabbkb consider putting in a pull request with these changes? Or since this is an older issue, maybe @amandawhitmire would want to develop a PR. Then the maintainers can decide if the changes are suitable for immediate or future merging into the lesson.

**Comment by amandawhitmire** [comment]
I'd be happy to finalize wording and submit a PR.

**Comment by amandawhitmire** [comment]
I'd like to suggest these changes, and will submit a PR to this effect:

After this lesson, you will be able to:
- Implement best practices in data table formatting  
- Identify and address common formatting mistakes
- Understand approaches for handling dates in spreadsheets
- Utilize basic quality control features and data manipulation practices
- Effectively export data from spreadsheet programs

**Comment by amandawhitmire** [comment]
The pull request has been completed, so this issue can be closed. ::thumbs up::

**Comment by fmichonneau** [comment]
Great, thanks! In your future contributions, if you add "fix #xxx" where the xxx represent the number of the issue (here it would have been "fix #197"), then the issue gets closed automatically when the pull request is merged! See [this page of the GitHub documentation](https://help.github.com/articles/closing-issues-using-keywords/) to learn more about it.
