### ISSUE TITLE
Updates to 04-quality control lesson

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/spreadsheet-ecology-lesson#20]
The 04-quality control lesson is designed to go through some things in Excel to show how you can do conditional formatting or sorting to look for outliers or mistakes in data.
- We need 'how to' information in this lesson for each section, both for the instructor and the learners
- This 'how to' needs to include how to do it on each OS, or pointers to tutorials for each
- We need exercises that use our survey data, which means we might need another tab in our Excel file.

**Comment by ethanwhite** [comment]
#25 does some of this, albeit for quality assurance instead of quality control

**Comment by ErinBecker** [comment]
@tracykteal Do we want to incorporate these additions into the lesson release this month or tag this "after-lesson-release"?

**Comment by ErinBecker** [comment]
http://www.datacarpentry.org/spreadsheet-ecology-lesson/04-quality-control/ Addresses much of this.
