### ISSUE TITLE
Spreadsheet data issue

### ISSUE THREAD

**Issue by binod52** [datacarpentry/spreadsheet-ecology-lesson#203]
1) This is just a proof reading here in 
http://www.datacarpentry.org/spreadsheet-ecology-lesson/01-format-data/
First line is first paragraph: "The most common mistake made is treating treating...."
The 'repeating' word is repeated and need to fix that.

2) Under the Data Organization in Spreadsheets (Quality Control), the Excel table given for the exercise and answer is different. (http://www.datacarpentry.org/spreadsheet-ecology-lesson/04-quality-control/).
The part of the exercise table (after shorting the data (weight_grams) from largest to smallest is

Cells that contain non-numerical values are not colored. This includes both the cells where the letter “g” was included and the empty cells. quality_control4, exercise2
![screen shot 2017-07-06 at 2 36 19 pm](https://user-images.githubusercontent.com/29214181/27931747-8f66b06a-6258-11e7-9cb1-0d296670ed45.png)
I think both tables should contain same data so that there won't be any confusion.

**Comment by bbolker** [comment]
The first issue (repeated word) is addressed by [this pull request](https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/199/commits)

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/224
