### ISSUE TITLE
Add info about what the lesson is not about in the first page for students

### ISSUE THREAD

**Issue by agbeltran** [datacarpentry/spreadsheet-ecology-lesson#205]
The instructor notes indicate that the lesson is *not* about data analysis but data organization (http://www.datacarpentry.org/spreadsheet-ecology-lesson/guide/).

I think this is useful information for students too, when listing the learning objectives on the main page (http://www.datacarpentry.org/spreadsheet-ecology-lesson/) to set the appropriate expectations.

**Comment by hoytpr** [comment]
Hi @agbeltran, 
It looks like this has been addressed in the lesson. Would you like me to close this or do have more you would like to add to the objectives?

**Comment by hoytpr** [comment]
Issue addressed.
