### ISSUE TITLE
Eliminate redundant phrases when referring to spreadsheet programs in the introductory lesson

### ISSUE THREAD

**Issue by agbeltran** [datacarpentry/spreadsheet-ecology-lesson#206]
The introductory lesson (http://www.datacarpentry.org/spreadsheet-ecology-lesson/00-intro/) refers a few times to spreadsheet programs and how they might differ, even if the general ideas are the same. It also reiterates points related to this that were mentioned in the setup lesson (http://www.datacarpentry.org/spreadsheet-ecology-lesson/setup/). I suggest streamlining the text to avoid repetitions.

**Comment by hoytpr** [comment]
Thanks again @agbeltran. I see what you mean that in the Introduction it says
"Commands may differ a bit between programs, but the general ideas for thinking about spreadsheets are the same."

and in the setup it says:
"Commands may differ a bit between programs, but the general idea is the same."

I suppose we could eliminate one of those lines, although setup is different from actually teaching.  But we are always looking for ways to streamline the lessons. Anyone else want to chime in?

**Comment by hoytpr** [comment]
closing #206
