### ISSUE TITLE
Follow data citation best practices when referring to the data to be used in exercises.

### ISSUE THREAD

**Issue by agbeltran** [datacarpentry/spreadsheet-ecology-lesson#207]
The setup section (http://www.datacarpentry.org/spreadsheet-ecology-lesson/setup/) provides the link to download the specific spreadsheet to be used for the exercises ( https://ndownloader.figshare.com/files/2252083).
It would be good to include a full data citation referring to the DOI (doi.org/10.6084/m9.figshare.1314459.v6), authors, etc.

**Comment by ErinBecker** [comment]
Closed with #214
