### ISSUE TITLE
Introduce 'exporting data' section earlier

### ISSUE THREAD

**Issue by agbeltran** [datacarpentry/spreadsheet-ecology-lesson#208]
The formats to export data are important throughout the lesson (e.g. CSV is mentioned in http://www.datacarpentry.org/spreadsheet-ecology-lesson/03-dates-as-data/ without having been introduced). I suggest changing the order of lessons and introduce the lesson 5 earlier (http://www.datacarpentry.org/spreadsheet-ecology-lesson/05-exporting-data/) or at least refer to it in advance.

**Comment by hoytpr** [comment]
Hi @agbeltran 
This issue has been around a while, and I agree with you. 

It looks like renumbering the filenames would work based on the Makefile. @tracykteal @cbahlai 
I can test this but would rather @fmichonneau or someone more familiar with the lesson structures change this, if others agree.

**Comment by hoytpr** [comment]
Rather than re-arrange episodes, a reformatting and re-wording related to issue #296 could include additional information on .csv files such that learners are aware of a preferred format for using spreadsheets as data-entry points. AFAIK modern spreadsheet software will open .csv files.
