### ISSUE TITLE
Keep pivot tables in lesson?

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/spreadsheet-ecology-lesson#21]
The quality control lesson overall needs some updates (https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/20)

In that lesson though, we have Pivot Tables. Is that something we should be teaching? It is a very useful Excel skill, and we can tie it to the quality control piece, but it also is starting to do things that would be done more reproducibly in R or SQL.

**Comment by tracykteal** [comment]
I'm +0 on this so interested in different perspectives.

**Comment by fmichonneau** [comment]
No strong feelings here either. I think they are useful to double check that data was entered correctly or get quick summaries but not for data analysis.

**Comment by ethanwhite** [comment]
Anything we're collectively +0 is probably something we shouldn't be teaching. I'd rather have more time to teach something else so I'm -0.5.

**Comment by apawlik** [comment]
I agree with @ethanwhite I think teaching Pivot Tables is actually pushing people towards the direction we don't want them to go (using Excel for data analysis and reporting). What I thought would be useful is an example of a problem with Pivot Tables ("and here is where things go wrong").

**Comment by tracykteal** [comment]
Since we would have to introduce pivot tables to be able to show what goes wrong with them, it seems best to just avoid much discussion of them. 

Created a PR with this change, and some commentary on issues with conducting analyses in spreadsheets.
https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/26

**Comment by ethanwhite** [comment]
> Since we would have to introduce pivot tables to be able to show what goes wrong with them, it seems best to just avoid much discussion of them. 

Agreed, but I actually think we should just avoid all discussion of them. I'll comment more in #26.

**Comment by tracykteal** [comment]
After discussion, it seems the consensus is just to take them out. Removed from lesson in https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/33
