### ISSUE TITLE
Issue #203 looks fixed but link to data is wrong

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/spreadsheet-ecology-lesson#220]
In issue #203 @binod52 shows that the downloaded semi-cleaned file from (http://www.datacarpentry.org/spreadsheet-ecology-lesson/04-quality-control/) had different data, which looks fixed in the images. However, the download link for the "semi-cleaned data" file now downloads the same "messy" file as in the previous lessons. No "survey_sorting_exercise" file is found in the data folder.

**Comment by tracykteal** [comment]
I put in a pull request to add the data. https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/224 and you could download it from here.

https://github.com/datacarpentry/spreadsheet-ecology-lesson/tree/sorting-data/data

It seems to match the screen shots.

Could you check to see that it works for the exercise? Thank you!

**Comment by hoytpr** [comment]
The folder with both files opens, but it isn't an automatic download.

**Comment by tracykteal** [comment]
Right, I put in the PR for the data, but not the link to the data. I've updated the link in the PR. 

The data from the PR will download automatically from https://github.com/datacarpentry/spreadsheet-ecology-lesson/blob/sorting-data/data/survey_sorting_exercise.xlsx?raw=true

**Comment by ErinBecker** [comment]
Closed with https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/224#event-1526393285
