### ISSUE TITLE
Add data for this lesson to figshare repo?

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/spreadsheet-ecology-lesson#23]
@ethanwhite what do you think about adding the messy data file now used in this lesson to the Figshare collection?

https://www.dropbox.com/s/5ncuacnd3arjitc/survey_data_tabs.xls?dl=0

**Comment by ethanwhite** [comment]
Yes, I think that's a great idea. Will try and get a new release with this and the big joined table done soon.

**Comment by tracykteal** [comment]
Thanks! Assigned to @ethanwhite

**Comment by ethanwhite** [comment]
Done:
http://files.figshare.com/2236371/survey_data_spreadsheet_messy.xls
