### ISSUE TITLE
New GitHub labels

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/spreadsheet-ecology-lesson#234]
I'd like to deploy the proposed set of GitHub labels for this repository. You can read about the [process for developing these labels](http://www.datacarpentry.org/2018-04-05-github-labels) and see the [list of labels in the handbook](https://docs.carpentries.org/topic_folders/maintainers/github_labels.html).

Before doing so, I'd like the input of the maintainers of this repository regarding on how to deal with existing labels in this repository. There are 3 options:

1. **start from scratch**: I delete existing labels and deploy the new ones. Labels currently assigned to issues will be lost.
2. **co-existence**: I deploy the new set of labels, leave the ones currently in use in the repository intact. The Maintainers re-assign issues to new labels and delete the old ones once you completed the transition.
3. **transition**: I deploy the new labels and I do my best to re-assign old labels to the ones

Please let me know your preference. If I don't hear from you within 2 weeks, I'll use the transition option.

**Comment by tracykteal** [comment]
Thanks @fmichonneau. We don't have too many outstanding issues here, so my vote would be to start from scratch. Looking forward to the new labels!

**Comment by fmichonneau** [comment]
Great. The new labels are now deployed for this repository!
