### ISSUE TITLE
Overall not enough content for the time allocated

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/spreadsheet-ecology-lesson#24]
We allocate about an hour or an hour and a half to this exercise, but there's currently not enough content to fill that time. Adding to the quality control materials https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/20 might help, but this is an important point to consider. 

We either need to expand the lesson or shorten the allocated time.

**Comment by apawlik** [comment]
@tracykteal I agree. At Utrecht people actually said it would be enough to have 15 minutes to work in groups to identify the problems and then maybe another 15-20 to discuss.

**Comment by zjsteyn** [comment]
One area that would add to time allocated can be additional exercises as proposed in issues 120 and 119 for instance.

**Comment by ErinBecker** [comment]
Just by way of record-keeping, I'm adding an "after-lesson-release" tag here just to indicate that this won't be incorporated into the lesson before publication at the end of this month. If you're planning on expanding the lesson significantly before lesson release, please let me know and I'll remove the tag!

**Comment by tracykteal** [comment]
Issues #119 and #120 have been addressed and included. Even with these additions, we have revised the expected time for this lesson to be about 30 minutes.  That matches the amount of content, is enough to appropriately address the topic and fits in well with the overall schedule. I'm going to go ahead and close this issue.
