### ISSUE TITLE
jump directly into looking at messy spreadsheet

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#242]
This lesson starts with some explanation of tidy data principles and then has learners look at the messy spreadsheet and make a list of problems with the formatting. Since this is the first lesson in the workshop, this leads to a very slot start to the morning. i've found that it's more engaging to give a very brief introduction to the goals of the spreadsheet lesson and then jump straight into the first exercise. The discussion of tidy data principles can then be part of the class discussion about that exercise.

**Comment by hoytpr** [comment]
@ErinBecker I'm not sure what happened to this, seems like nothing really happened. But it's important to keep students engaged from the beginning. The merge from @rgaiacs is not addressing your comment nor does my "push". Thanks for the feedback. Do you want to create a PR for this?

**Comment by hoytpr** [comment]
Update: just taught this again, and after quickly getting into the messy spreadsheet, we had a discussion, and then went to the semi-clean spreadsheet. Later we showed how the DM, DO , and DS could be split, and used the example of "list" function under "quality control" as an example of how to protect data entry. This seemed to go over very well.

**Comment by hoytpr** [comment]
In the resolution to issue #296  this will likely be addressed.

**Comment by hoytpr** [comment]
Too many proposed changes to justify keeping this issue. Closing #242
