### ISSUE TITLE
Page build fails after merge

### ISSUE THREAD

**Issue by hoytpr** [datacarpentry/spreadsheet-ecology-lesson#245]
Fellow maintainers @cbahlai and @tracykteal . 
I merged PR #237 after inspecting it, but received an email saying  there was a page build failure. 
I reverted the merge immediately as #243 . Following instructions on "general" page build failures  I noticed I did not have a verified email, which might prevent PRs from working (https://help.github.com/articles/generic-jekyll-build-failures/). After adding a GPG to my Github account, and verifying my email, I tred again as PR #244 but got the same error. 

Some sleuthing suggests that the page stopped building correctly between June 12, and June 19, and could be associated with the _config.yml file. I could use some help here. The lesson seems intact for the most part.

**Comment by tracykteal** [comment]
Thanks @hoytpr. I'm just headed offline for a couple of days, but since it's building ok for now, I'll sleuth when I'm back. Maybe @cbahlai will have a chance to take a look though.

**Comment by fmichonneau** [comment]
fixed with ee6f910d0e8cc72eecffe545722109563bac128b
