### ISSUE TITLE
Change xls to xlsx

### ISSUE THREAD

**Issue by jennybigman** [datacarpentry/spreadsheet-ecology-lesson#251]
I was thinking that in the episode of 05-exporting-data.md, at the bottom, the "xls" in the below portion could also be "xlsx". 

"A note on R and xls
There are R packages that can read xls files (as well as Google spreadsheets). It is even possible to access different worksheets in the xls documents."

**Comment by hoytpr** [comment]
Hi @jennybigman 
I think it would be appropriate if you put in a PR referring to ".xls or .xlsx". Both suffixes might be used depending on the individual operating system, or whether Microsoft, or Open Office, or LibreOffice is used.  Thanks for your feedback and hope to see a PR from you soon.

**Comment by hoytpr** [comment]
Just a friendly reminder @jennybigman

**Comment by hoytpr** [comment]
Solved #251 solved #257
