### ISSUE TITLE
Slidedeck of lessons?

### ISSUE THREAD

**Issue by isteves** [datacarpentry/spreadsheet-ecology-lesson#252]
Hi there, are there already slidedecks associated with the lessons?  If not, I'd like to create some.  Would it be worth linking to them in the lessons?

**Comment by hoytpr** [comment]
Hello @isteves, I don't know of any slidedecks at the moment. It would be great if you wanted to put some slides up for people to use. I can't say for certain if yours would be directly linked in the lesson, as everyone's slides are different, but it would be great to have some links to slidedecks. Maybe the other maintainers can comment about this. Thanks very much!

**Comment by isteves** [comment]
Hi @hoytpr, in the end I ended up drawing from a few other resources as well to create the presentation for our workshop: https://github.com/ecodatasci-tlv/spreadsheets

Feel free to use it as a template/link it elsewhere (or not!).  In any case, I figure it's work parking the link here in this issue 😄

**Comment by hoytpr** [comment]
Thanks @isteves the slides are great.  Unfortunately I can't leave an issue open for the link, so I've created a project and put your link to the slides there. Thanks again!

**Comment by isteves** [comment]
Sounds good, thanks!
