### ISSUE TITLE
Lesson Contribution

### ISSUE THREAD

**Issue by sheraaron** [datacarpentry/spreadsheet-ecology-lesson#254]
There is a typo in "Data organization in Spreadsheets for Ecologists"-Quality control

Above "Key points" near the bottom, the sentence "It is nice to do be able to do these scans in Spreadsheets" should be "It is nice to be able to do these scans in Spreadsheets". The word "do" after "It is nice to" should be deleted.

Another one is "Data cleaning with OpenRefine for ecologists --- working with OpenRefine"

When I tried to do faceting, I click Facet - Text facet, the OpenRefine went on working and working without producing any results.

I used the file suggested by the lesson. Maybe the file is too big?

**Comment by hoytpr** [comment]
Hi @sheraaron , just a friendly reminder if you want to try a pull-request.

**Comment by hoytpr** [comment]
And if you do make a PR @sheraaron go ahead and include the other typo on "Data organization in Spreadsheets for Ecologists"-Quality control: there is a repeated "a" at the top under "Quality assurance" specifically: "To control the kind of data entered into a **a** spreadsheet we use Data Validation"

**Comment by sheraaron** [comment]
@hoytpr I am on The Carpentries staff and created that issue for a learner who was doing their lesson contribution as apart of their checkout process 😄

**Comment by hoytpr** [comment]
@sheraaron Well good work! If you're not comfortable with a PR yet, I can do the typos for you, although I'd encourage you to try. 
I'll also check the faceting issue you mention. Thanks for your contributions.

**Comment by sheraaron** [comment]
@hoytpr thanks for the encouragement 😄 I am comfortable however, when I submit these, I will not be creating PR's, I just create the issues 😄 so that the person will get their credit for checkout. Thanks 😃

**Comment by sheraaron** [comment]
# #

**Comment by tracykteal** [comment]
Closed by https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/263. Thanks @hoytpr
