### ISSUE TITLE
Step1 for exercise 1 for Conditional formatting 

### ISSUE THREAD

**Issue by kmadzima** [datacarpentry/spreadsheet-ecology-lesson#256]
There is an error in the Quality Control Episode of the Data Organisation in Spreadsheets for Ecologists
https://datacarpentry.org/spreadsheet-ecology-lesson/04-quality-control/index.html  

**Description of the Error**
The current **step 1** suggests that users must click **FORMAT>Conditional Formating** but the current versions of **Microsoft Excel in Office 2016 or Office 365** no longer have the **Format** as a main menu option. There is also a a missing **t** in the spelling for Formatting.

**Suggested Correction**
**The corrected version should read as follows:**
1. In the main Excel menu bar, click Home tab > Conditional Formatting... Click the + to add a formatting rule.
 

---
This is a submission for Instructor checkout

**Comment by hoytpr** [comment]
Hi @kmadzima and thanks for your contribution. It's always great to get rid of typos (they seem to never end). Also you are correct; Format> Conditional Formatting is incorrect, even in Excel 2013 (which I'm still running). In 2013 you click the Home tab, then select "Conditional Formatting" under Styles, and the drop down menu takes you to "new Rule".  Do you want to try a Pull Request to fix these issues? We (Maintainers) don't usually create and merge our own PRs. It would be great if you could try. 

Thanks again and let me know what you are comfortable with attempting. 
Peter

**Comment by kmadzima** [comment]
Dear Peter

I have just submitted a pull request for the issue. I am also willing to
continue making contributions.

Kind Regards

Kudakwashe Madzima

**Comment by hoytpr** [comment]
Hi @kmadzima it looks like you closed this issue almost as soon as you put in the pull request. When you do that, your Pull Request won't work. Do you want to reopen this? It looks good and I should be able to merge the PR as soon as you reopen it. 
Thanks very much for contributing!
Peter

**Comment by hoytpr** [comment]
Thanks @kmadzima !
