### ISSUE TITLE
submitted by email

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#260]
Quality Assurance

The challenge with this lesson is that the instructor version of the spreadsheet software is going to look different that about half of the room.

Concluding points

Now your data is organized so that a computer can read and understand it. This will let you use the full power of the computer for your analyses as we'll see in the rest of the workshop.

While your data has been neatly organized, still it might have some error and missing data or other problems.

**Comment by hoytpr** [comment]
@ErinBecker Good comments: Not sure if the differences will be significant enough to lose learners. An alternative is to give students an Excel spreadsheet which when opened in most software, will look similar. 

The concluding points are good, however the data validation and dates as data sections are supposed to address this partly, particularly as this lesson becomes more influenced by genomics. Please submit a PR if you want these changes made. 

The list of ways that problem can occur in spreadsheets (including the issue #230  by @ctb) are good references.

**Comment by ErinBecker** [comment]
Thanks for the review @hoytpr. These aren't my comments, but were submitted by an instructor trainee through email. That trainee is not comfortable interacting with the GitHub user interface. I'll leave it to you and the other Maintainers for this lesson to decide if it's worth your time to put in a PR for these suggestions.

**Comment by hoytpr** [comment]
Ahhh. Thanks @ErinBecker,  I also received some suggestions by @Sheraaron that turned out to be either from, or for, students. It would be great if we could put a label on these submissions ("checkouts/training"), otherwise they look like the are coming directly from you.  As far as I know the only other maintainers for this lesson are @cbahlai and @tracykteal.

**Comment by hoytpr** [comment]
This lesson will potentially be undergoing a re-formatting from issue #296 where the images will be Mac-based. Although this doesn't solve the issue of images being potentially different for half the class, the alternative (adding images from all software and even different versions of the same software) is untenable as a lesson. This lesson has a lot of discussion, and it may be appropriate to create a page of images representing **several** software, that can be used as a reference for instructors and helpers during workshops. But this won't be an exhaustive list regardless.

**Comment by hoytpr** [comment]
This issue has languished (during the pandemic) and unfortunately the situation is worse now that MS Office 365 is in wide-use (not even considering spreadsheets on peoples phones now). Maybe we should consider **_requiring_** the students to use a specific spreadsheet. Would "LibreOffice Calc" work universally?

We could develop pages of examples of bad behavior by individual spreadsheets (with **matching** images) as "Extras". 

An advantage of requiring a specific spreadsheet like Libre Office "Calc" is we could stop spending so much time with "discussion" in this workshop, and do more hands-on work.

**Comment by hoytpr** [comment]
Closing this due to the number of different spreadsheet software. We could try to create images for different software (e.g. Mac and PC) but not all spreadsheet software can be represented here.
