### ISSUE TITLE
Font size in messy spreasheet

### ISSUE THREAD

**Issue by dravery** [datacarpentry/spreadsheet-ecology-lesson#271]
In Data Organization in Spreadsheets for Ecologists: Setup
https://datacarpentry.org/spreadsheet-ecology-lesson/setup.html

The downloaded file is:
https://ndownloader.figshare.com/files/2252083

The examples in the worksheets are all useful, but the formatting and location of the examples make it difficult to easily display the lesson and interact with the spreadsheet.

The defaults associated with this file are 50% zoom and in many cells the font and size in the first two rows is Arial 10 pt. At 50% zoom, the 10 pt font is just about impossible to see. One useful exercise while teaching this lesson is to 'live code' corrections for the various issues. Because variables are most often defined on the first row (unless 'skip rows' is included in the data import lesson), this is the logical place to input corrections. With the default font size for empty cells in these first rows (and perhaps elsewhere) at 10 pt, live coding consists of several extra steps to view corrections because the font size for each cell needs to be increased substantially. 

In addition, it is clear that the data are formatted oddly and not in a useful way for R so the first two columns serve only to offset the various data boxes. This is really more of an annoyance when displaying the data. There isn't a need to have every potential formatting issue included. Leaving the first two rows blank serves the same purpose. Thus, to make displaying easier, these first two columns should be removed.

Here is a revised messy data file. Perhaps it can replace the one in the lesson and make things a bit easier.
[Copy of survey_data_spreadsheet_messy.xlsx](https://github.com/datacarpentry/spreadsheet-ecology-lesson/files/3303204/Copy.of.survey_data_spreadsheet_messy.xlsx)

**Comment by hoytpr** [comment]
That's a great analysis @dravery of the messy spreadsheet.  We can work with you to address some of these issues.  And supplying a reformatted example was great. Although @cbahlai or @tracykteal might want to weigh in on this, can we start off by figuring out why some things that don't match on my system? When I use Excel or Calc to open `survey_data_spreadsheet_messy.xlsx` (just now downloaded from the link in your post), the default zoom levels are as you state (50% for worksheet "2013" and "2014, but 100% for worksheet "dates").  However, the fonts are Arial 24-point on "2013" and "2014", and Arial 16-point for "dates".  We should identify why you are getting smaller fonts first. Are you using a Mac? I can check the spreadsheet on a Mac if that's what you are using.

**Comment by dravery** [comment]
Hi @hoytpr . I use Windows so the issue with fonts is not with an OS (although that can be an issue). To see the font size issue, check the original downloaded messy file first 2 rows. There are many cells that are Arial 10 pt. The worksheet overall states Arial 20 pt (2013) and Arial 24 (2014), but it's not the case in all cells.

**Comment by hoytpr** [comment]
Hi @dravery and thanks for responding. It turns out we discussed this at the maintainers meeting, and the messy spreadsheet is created to be intentionally annoying! The point (or one of the points) of this lesson is to show how there can be **hidden** problems when using Excel spreadsheets. You're reaction is what the original authors intended, and we appreciate your feedback!  The consensus right now is to keep the file as is. I hope you understand.

**Comment by dravery** [comment]
All good! Something to add to the local lesson plan :-)
