### ISSUE TITLE
Clarify Data Validation screen grabs are from MS Excel

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/spreadsheet-ecology-lesson#277]
In the instructions on how to set up Data Validation, I would recommend noting that these screen grabs are from MS Excel, and that this may look different depending on what spreadsheet platform you are using (Libre Office, Google Sheets, etc.).

**Comment by maneesha** [comment]
Looking back through the material, I see in the intro information for this lesson that it states that we are using MS Excel as an example throughout.  So I am OK closing this issue.

**Comment by hoytpr** [comment]
Thanks @maneesha
