### ISSUE TITLE
Possible typo in drop down list sample?  

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/spreadsheet-ecology-lesson#278]
The demonstration dropdown list here: 
![image](https://user-images.githubusercontent.com/829690/69009927-3887ff00-0928-11ea-897a-1729ed89a49a.png)

includes the items:

* Dipodomys spectabilis
* Dipodomys merriami
* Dopopdomys ordii

It looks like the third item on the list is a typo.

**Comment by hoytpr** [comment]
Thanks @maneesha 
This is (to my understanding) an intentional misspelling. 
Please verify @tracykteal or @cbahlai

**Comment by hoytpr** [comment]
Maneesha, 
This appears to be an intentional mis-spelling. I'm going to close this issue, but thanks very much for pointing this out!

**Comment by maneesha** [comment]
Thanks. I'll defer to you all as lesson maintainers, but I don't think it makes sense to me.
The drop down is presented in the context of data validation, which has the goal of ensuring that the person entering data does not make typos. If it is indeed an intentional typo used for teaching purposes, it should be identified as such in the lesson material.

**Comment by hoytpr** [comment]
Fair enough, please feel free to send in a PR! 

By re-opening, maybe we can get some more discussion!

**Comment by hoytpr** [comment]
Also good to acknowledge that this issue, taken outside the context of the OpenRefine lesson, is simply a typo. @maneesha I've attached an image to replace the one in the lesson. If you could find the time to put this into a PR, I would appreciate it. 
![drop_down_list](https://user-images.githubusercontent.com/5910884/70572958-81695700-1b66-11ea-96c7-95ccc4ea321d.png)

**Comment by hoytpr** [comment]
After teaching this today. The spelling error is not pertinent to the base lesson. New file named drop_down_list2.png was created to protect any other lesson dependencies.
