### ISSUE TITLE
Crediting authors for lesson?

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/spreadsheet-ecology-lesson#280]
The Spreadsheets lesson is the only lesson that has credited authors at the top of the lesson.  These names are not consistent with the current lesson maintainers.  Should this change to reflect the current active maintainers?  Was this intended to acknowledge only the original lesson developers?

**Comment by hoytpr** [comment]
Hi @maneesha ,
Your attention to these lessons is appreciated. It is true these are about the only lessons with authors listed. But, any decision to remove the authors names, or to place them somewhere else in the acknowledgements of the lesson, is not a decision for me. The authors did a tremendous amount of work and I am in awe. 

Maybe @cbahlai or @tracykteal or @ErinBecker or @fmichonneau or @apawlik or @ethanwhite can help you with this one. I'm quite happy to help in any way, but if no one responds, I'm going to take that as a "leave it alone" message. Your question is legit regarding consistency, just not one for me to answer. I hope you understand.

**Comment by tracykteal** [comment]
Thanks @hoytpr! These lessons did come together when we were listing authors, and we do have an updated format for credit know, including publication of lessons. I'll send an email to the authors who are listed to what we want to do here. Thanks for your appreciation of that @hoytpr.

**Comment by tracykteal** [comment]
Talked with @cbahlai and she's fine with removing the 'Author' listing on the lesson.

**Comment by hoytpr** [comment]
Thanks so much for your help @tracykteal !

**Comment by tracykteal** [comment]
@apawlik is fine with it too, so we can put in the PRs to make this update.

**Comment by hoytpr** [comment]
Closed with appreciation to everyone involved.
