### ISSUE TITLE
using OKFN's frictionless data standards?

### ISSUE THREAD

**Issue by steltenpower** [datacarpentry/spreadsheet-ecology-lesson#285]
In the 02 page I read "metadata should NOT be contained in the data file itself", but isn't (part of) OKFN's so-called friction-less data (maybe known for their related goodtables.io service) going against that? This frictionless data and some of the tools deserve to be a part of "Quality Control
" on the 04 page if you ask me.

Let me know what you think.

Please delete the text below before submitting your contribution. 

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by tracykteal** [comment]
Thanks @steltenpower. That's a good point. There are these types of resources that we can reference. There are decisions to be made about metadata, depending on how and where you're sharing, so we can point learners towards these resources. For this particular point, what would be a good page for reference?

**Comment by lwinfree** [comment]
Hi @steltenpower! I work with Frictionless Data, so I can comment on that. We don't propose having metadata in the data file, so we are in agreement with the quoted text "metadata should NOT be contained in the data file itself". To handle metadata, we suggest packaging your data file with a metadata file (written in JSON), and we call that package a 'data package'. Check out more here: https://frictionlessdata.io/field-guide/ Does that help?

**Comment by steltenpower** [comment]
Thanks for bringing clarity to that @lwinfree .
While reading your comment I realize where I got the confusion from: JSON is turned into JSON-LD by adding metadata into the data file.
