### ISSUE TITLE
[email feedback] suggestions to improve the lesson

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/spreadsheet-ecology-lesson#290]
1) examples on how to use Data Validation to strengthen the quality of the data.
In paragraph: "... if you use a list of options to restrict data entry, the spreadsheet will provide you with a drop-down list of the available items" the course should be aware that we are now working with an Excel table as ".xls [Compatibility Mode]". In such mode, the drop-down menu set as a Data Validation (list) is not visible to the user. This should be mentioned, so students can try the beauty of a list in a secondary file that is .xlsx

2) at one point, we are asked to export the .xlsx table into a .csv file. In the latest version of Excel, the save as... option to export a table in .csv is no longer available as "Windows comma separated (.csv)". It is unclear to me how the newest version for .cvs export in Excel performs compared to legacy. See dets here. It would be great for an expert user to check for us which "Save As" option we should use to safely export .csv tables

3) Scatterplot facet
Exercise:
Examine the scatterplots overall. Do the patterns make sense?
Why does the scatterplot for recordID vs period have the pattern it does?

--> in spite having transformed the recordID column and the periodID column into Numbers values, they do not appear in the Scatterplot facet. only yr mo and dy appear in the matrix

**Comment by hoytpr** [comment]
Hi @fmichonneau and thanks for going through the lesson and finding these issues. I can answer #2 immediately. The latest version of Excel uses "Export >>> "Change File Type >>> CSV (Comma delimited) (*.csv).  We will need to mention these differences! This is an Office 365 issue (I think). The #1 and #3 issues will need a little research but luckily I have both Office 365 and older versions of Excel. ☺

**Comment by hoytpr** [comment]
Closing this as we move to a rewrite with issue #296
