### ISSUE TITLE
Where year 2015 in tab '2014' is coming from in the messy data is not clear nor explained

### ISSUE THREAD

**Issue by anenadic** [datacarpentry/spreadsheet-ecology-lesson#291]
I assume that the person who entered data in 2014 copied in some of the 2014 data they forgot initially to include and this copying occurred in 2015 but they did not include the year in the dates so they were saved by Excel as dates in 2015. 

But is this assumption true? This is what I tell students.

Lesson affected is 03-dates-as-data and also I try to explain what the data contains in lesson 01-format-data early on.

**Comment by anenadic** [comment]
Lesson affected is 03-dates-as-data and also I try to explain what the data contains in lesson 01-format-data early on.

**Comment by hoytpr** [comment]
Hi @anenadic the answer is "yes", you are exactly correct. In the exercise, the data was copied in 2015, and so is converted to the year 2015. It says: "You can see that even though you wanted the year to be 2014, your spreadsheet program automatically interpreted it as 2015, **the year you entered the data**.". 

Do you have a suggestion for making this more clear?

**Comment by anenadic** [comment]
It is not clear who 'you' is in this case - the data has been collected in 2013/2014 by 2 different researchers and not the participants of the workshop. So, I'll try and do a pull request to suggest changes I'd make for the maintainers to review.

**Comment by anenadic** [comment]
To be honest, I'd also get rid of the 'dates' tab from the data as it is potentially confusing and does not resemble a 'dataset'. For the lesson on dates, instructor can refer to the '2014' tab to point out the problem with dates and then copy the problematic 'plot 3'  table into a separate 'dates' tab if necessary for them to play with/work with dates (and ask the participants to do so too).

**Comment by anenadic** [comment]
Created PR at: https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/293

**Comment by hoytpr** [comment]
Fixed with meerge #293
