### ISSUE TITLE
dates "in the future" are no longer in the future

### ISSUE THREAD

**Issue by elenaoz** [datacarpentry/spreadsheet-ecology-lesson#295]
The Dates as Data episode has an example in a section titled "Storing dates as YEAR, MONTH, DAY". The spreadsheet image has set of samples collected in July, 10,14, 15 and 19. The text below the image explaining how excel handles those dates says that it sees july 19 as 1-july-2019. And states this is "in the future" but it is not anymore. I'm just learning Git, and don't feel confident using it to put in a pull request (if that's what its called)
Here's the link to the page [https://github.com/datacarpentry/spreadsheet-ecology-lesson/blob/gh-pages/_episodes/03-dates-as-data.md](https://github.com/datacarpentry/spreadsheet-ecology-lesson/blob/gh-pages/_episodes/03-dates-as-data.md)

**Comment by hoytpr** [comment]
You are correct @elenaoz and thanks for pointing this out! I would be happy to help you with a pull request (I certainly was not and am not a Git expert) but if you really aren't comfortable yet (and that's OKAY), I'll fix it tomorrow. Thanks again!

**Comment by hoytpr** [comment]
Thanks @elenaoz for your contribution! The image is much better now!
Here's a link to the Software Carpentries "Git-Novice" lesson if you want to learn more about pull-requests (they aren't as easy as some people think). 
http://swcarpentry.github.io/git-novice/
Feel free to contact me if you want to practice pull requests.
