### ISSUE TITLE
Broken weblink in contributing.md

### ISSUE THREAD

**Issue by kbriney** [datacarpentry/spreadsheet-ecology-lesson#301]
The link to the "How to Contribute to an Open Source Project on GitHub" under the ["Using GitHub" heading](https://github.com/datacarpentry/spreadsheet-ecology-lesson/blob/gh-pages/CONTRIBUTING.md#using-github) is giving a 404. 

The link goes to [this page](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) but it looks like the updated URL is [https://app.egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github](https://app.egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github).

**Comment by hoytpr** [comment]
Hi @kbriney and thanks for catching that! This is and older lesson and that is an old link. Would you like to submit a PR to get credit for catching this and fixing it? If you'd rather we just fix it, that's fine too.

**Comment by kbriney** [comment]
I would love to submit a PR except I've completely forgotten how to actually do that, so it will be faster if you fix it. (This is completely relevant to which link is broken because it's for the tutorial on how to do a PR.)

**Comment by hoytpr** [comment]
No problem and yeah, it's ironic!
I'll fix it and we can walk you through it if you want.

**Comment by kbriney** [comment]
I'm getting a colleague at work to help walk me through the process. I have a suggestion I want to make to the curriculum, so I will see how things go with that. But thanks for the offer.

**Comment by hoytpr** [comment]
Great! I went ahead and fixed the link, but please feel free to make a suggestion.

**Comment by hoytpr** [comment]
Closed after PR and new lesson release.
