### ISSUE TITLE
Broken link in Data Cleaning with OpenRefine Introduction

### ISSUE THREAD

**Issue by ckearney07** [datacarpentry/spreadsheet-ecology-lesson#303]
The reference link for GREL under [Basics of OpenRefine ](https://datacarpentry.org/OpenRefine-ecology-lesson/00-getting-started/index.html) has moved to  https://docs.openrefine.org/manual/grelfunctions/ .

**Comment by hoytpr** [comment]
Hi @ckearney07 and thanks very much for catching this. This isn't the home base for the OpenRefine lesson, but we appreciate you anyway! The lesson you really want to post the issue with is:
https://datacarpentry.org/OpenRefine-ecology-lesson/00-getting-started/

It looks like they have a redirect in place, but you might want to ask them at:
[OenRefine-Issues](https://github.com/OpenRefine/OpenRefine/issues) to make this fix.

**Comment by ckearney07** [comment]
Sorry about that! And thanks for the info. Thanks!
