### ISSUE TITLE
Suggestion for more on the DATE function

### ISSUE THREAD

**Issue by jwrigs** [datacarpentry/spreadsheet-ecology-lesson#308]
Hello! This was a great lesson to demo. 

One item I ran into as both a learner myself and an instructor is the the DATE function. The lesson sort of slides over it in "Dates as Data" episode. DATE is such an odd function for most folks. Yet, it seems like it should be intuitive based on the name. There are two reasons for adding a bit more for the DATE function.

##Reason 1
The data function allows us to deal with weird things and dates that may not be strictly numerical (ex. Leap Years). It allows us to calculate with dates as well as display them

##Reason 2
Although having all the date fields in one column is not ideal - it's often how secondary users (ex. clients) like it formatted for final outputs. Therefore, it's really useful to include a brief direction for the DATE function. This could be super short at the very end of the lesson and emphasized to be part of a final, human-readable product rather than for analysis-friendly sheets. It could even have a quick exercise-solution box. 

Thanks for considering and making a great lesson!

**Comment by hoytpr** [comment]
After some discussions, it seems like we are not trying to teach how to use Excel, but rather how to prevent it from changing the raw data. I'll close this for now.

**Comment by jwrigs** [comment]
Thanks Pete! Apologies for not getting back to you. Since the holidays and the fires here in Colorado, we’ve been hopping. Many well wishes for you spring!

Jordan
