### ISSUE TITLE
Including google sheets as a possible spreadsheet program

### ISSUE THREAD

**Issue by sstevens2** [datacarpentry/spreadsheet-ecology-lesson#310]
We mention excel and libre office and I think it would be good to also include google sheets.  This is becoming more and more a common spreadsheet program for researchers to use.  I use it a lot more than excel.

**Comment by hoytpr** [comment]
I agree! Do you want to put in a PR? Otherwise I can fix it.

**Comment by sstevens2** [comment]
If you are up for the fix, I'd appreciate it as I'm a bit behind in prepping to teach it for next week.

**Comment by hoytpr** [comment]
Thanks @sstevens2
