### ISSUE TITLE
Reference for spreadsheet organization (Broman and Woo)

### ISSUE THREAD

**Issue by sstevens2** [datacarpentry/spreadsheet-ecology-lesson#311]
I'll keep looking as I prepare to teach but I've not yet seen this journal article referenced and it is a favorite of mine on spreadsheet organization - [Data Organization in Spreadsheets by Broman and Woo](https://doi.org/10.1080/00031305.2017.1375989)

**Comment by hoytpr** [comment]
It looks like a great article to me. But we are teaching lot of these in the workshop already aren't we? If we decide to "endorse" a specific book, we may need to get permission from the authors, and maybe run it by the CAC. What do you think?

-p

**Comment by sstevens2** [comment]
Yes, many of the principles are already included - this journal article sums them up nicely so might be good to point to it.  We can ask the authors if they are okay with us including a link to it? - @kbroman is a Carpentries instructor at my local Uni and @karawoo has taught Carpentries workshops as well.

I'll leave it up to you if you'd like to ask the CAC, I'm not sure.  Might depend on if you think it is a big change?  I was thinking maybe including it in a callout with the [tidy data article](https://www.jstatsoft.org/article/view/v059i10) at the end of the [formatting data tables episode](https://datacarpentry.org/spreadsheet-ecology-lesson/01-format-data/index.html)

**Comment by kbroman** [comment]
We’d be glad to have you mention the article. It’s licensed CC-BY-NC-ND; there’s also a peerj preprint licensed more liberally, CC-BY, https://peerj.com/preprints/3183/

I wouldn’t think you’d need to “endorse” the article, and I don’t think there should be any requirement that one ask authors for permission to cite their work.

**Comment by hoytpr** [comment]
Sounds good to me. 
I'll set it up asap. Having serious computer problems today (Currently in BSOD territory).
