### ISSUE TITLE
Spreadsheet ecology lesson

### ISSUE THREAD

**Issue by raisaionin** [datacarpentry/spreadsheet-ecology-lesson#324]
I am preparing for the Carpentries certification. I will be teaching "Data Organization in Spreadsheets for Ecologists". I found only a few sample files I could use, and those are not very informative. Are there any more files for demos?
For example, this webpage, [https://datacarpentry.org/spreadsheet-ecology-lesson/02-common-mistakes/index.html](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdatacarpentry.org%2Fspreadsheet-ecology-lesson%2F02-common-mistakes%2Findex.html&data=05%7C01%7Craisa.ionin%40nih.gov%7C1956077fb59e4a8732ec08db0faab45c%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638120998087057391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Zj4wSscgBzngRxq6qZKCSAYxI9W1M9KGWX90%2FSau7tM%3D&reserved=0), contains a section on using multiple tables. 
There is only an image of multiple tables. I would like to have an original file for demo.

There are no samples for other sections at all. For example, I want to demonstrate Using problematic values and Inclusion of metadata. There are no samples.

Every lesson has text, explanations, but then there are only images. It's OK if you just read it, but not enough if you actually teach this material. It will be great if there are files for every image used, where trainees could practice, as well as trainers demo.

**Comment by tobyhodges** [comment]
Thank you for raising this @raisaionin. It prompted the Curriculum Team to reassess the recommendations for starting points in this lesson for teaching demos, and to open https://github.com/carpentries/instructor-training/pull/1481. The _Formatting problems_ episode will not be recommended for teaching demos in future.

For anyone is preparing to teach this lesson in future, during a workshop the episode is intended only as a resource to be referred to in discussion following [the exercise in the preceding _Formatting data tables in spreadsheets_ episode](https://datacarpentry.org/spreadsheet-ecology-lesson/01-format-data/index.html#exercise). As the exercise text describes, learners should download and use the messy example file for that exercise, and the Instructor can then use the same file as a basis for discussion of the points summarised in _Formatting problems_. 

See [the Instructor Notes for the lesson](https://datacarpentry.org/spreadsheet-ecology-lesson/guide/index.html) for more guidance on how the lesson is intended to be taught in a workshop. Those Instructor Notes informed our decision to stop recommending some of the episodes from this lesson for teaching demos.
