### ISSUE TITLE
Consider more current resources for additional learning

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/spreadsheet-ecology-lesson#336]
### How could the content be improved?

The [spreadsheets intro lesson](https://datacarpentry.org/spreadsheet-ecology-lesson/00-intro.html) suggests [Head First Excel](https://www.amazon.com/Head-First-Excel-learners-spreadsheets/dp/0596807694/), published by O’Reilly for additional learning.  This book is 14 years old (publication date April 2010). I do not use Excel but I am assuming much of the content is outdated. Consider replacing this with a more current resource.

**Comment by maneesha** [comment]
Note this is essentially a duplicate of [this issue from the social science curriculum](https://github.com/datacarpentry/spreadsheets-socialsci/issues/168).

**Comment by metut** [comment]
Hi @maneesha, thanks for raising this issue to our attention! @fontikar and I just updated the linked resource to something much more current.

@josenino95 tagging you in case you'd like to update your #168 issue, as well

Thanks!
Mary

**Comment by josenino95** [comment]
Hi @metut. Thank you for pointing out an updated resource here. I'll check it out with the maintainer team and also update our lesson!
