### ISSUE TITLE
Broken link to metadata resource 

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/spreadsheet-ecology-lesson#340]
### How could the content be improved?

In the [Inclusion of metadata](https://datacarpentry.org/spreadsheet-ecology-lesson/02-common-mistakes.html#metadata) section the link to Research Data [MANTRA](https://datalib.edina.ac.uk/mantra) is broken.  

### Which part of the content does your suggestion apply to?

https://datacarpentry.org/spreadsheet-ecology-lesson/02-common-mistakes.html#metadata

**Comment by fontikar** [comment]
New links that are broken

https://mantra.ed.ac.uk/

https://mantra.ed.ac.uk/libtraining.html

**Comment by metut** [comment]
Thanks so much for pointing this out, @maneesha! This issue is now resolved :)
