### ISSUE TITLE
Good formatting example contains troublesome formatting (possible pedantry)

### ISSUE THREAD

**Issue by richfitz** [datacarpentry/spreadsheet-ecology-lesson#37]
In the "avoid highlighting" section, the "good formatting" example contains at least one metadata row above the table ("Plot: 2").

![good formatting](https://raw.githubusercontent.com/datacarpentry/spreadsheet-ecology-lesson/gh-pages/fig/good_formatting.png)

(`fig/good_formatting.pdf`)

With the focus of the examples around machine-readability, this sort of thing makes ingest harder as the rows need to be skipped.

I could just be being overly sensitive though having waded through a bunch of spreadsheets recently :)

**Comment by tracykteal** [comment]
Thanks, excellent catch. That is indeed a screen shot of the bad example. Although it would have been OK if I'd cropped it better. I'll leave this issue open and update that screen shot.

**Comment by ErinBecker** [comment]
Fixed with #142
