### ISSUE TITLE
Update markdown processor to kramdown

### ISSUE THREAD

**Issue by qjcg** [datacarpentry/spreadsheet-ecology-lesson#44]
As described in datacarpentry/python-ecology-lesson#45.

**Comment by ErinBecker** [comment]
The issue referenced above says that redcarpet will no longer be supported as of May 2016 (a year ago). @qjcg any update on the status of this issue? Should this be done before lesson publication at the end of this month? @tracykteal

**Comment by qjcg** [comment]
Hey @ErinBecker ! Glancing at this repo's [_config.yml](https://github.com/datacarpentry/spreadsheet-ecology-lesson/blob/gh-pages/_config.yml), it appears that there is currently no `markdown:` field, so we're currently using the right Markdown processor, `kramdown`, by default. At the time I filed this issue, I believe we were explicitly using `markdown: redcarpet`, but the lesson template has been rewritten since then. 

I believe therefore that there's nothing to be done on this now, and that it's safe to close this issue (and the corresponding issues in the other datacarpentry repos using the new template).

**Comment by ErinBecker** [comment]
Great, thank you @qjcg.
