### ISSUE TITLE
Idea for common spreadsheet errors: Using bad null values

### ISSUE THREAD

**Issue by apreshill** [datacarpentry/spreadsheet-ecology-lesson#45]
Hi all,

I really appreciate this lesson in particular, and have shared it with lots of other teams! One thing to consider in the "using bad null values" section are the reasons why people use -999 or other non-NA missing value codes. I have done this is in the past with (some) good reasons. In human subjects research (where I work), we need to track and report the reason any value is missing, so I differentiate between active versus passive missing data: active is when missing data is assigned a value (with good and bad options here, but the idea is that we know it is truly missing); passive missing data is data left blank. 

Passive missing data is a red flag that we have to go back to the file and figure out what happened. Sometimes we rescue the data and it was just missed in the initial data entry, and sometimes it is actively missing. The problem is, if you use R (like I do) and you use NA as your active missing data code (meaning that data is truly missing), it is difficult to tell active from passive missing data if you read in this kind of data file. I think this is usually why -999 or other values _may_ be used- it is a way to have a placeholder to say "yes this is missing- no detective work required here." But as you guys note, it is dangerous to have those values mixed in with the true non-missing values in the analysis variable. 

One way around this problem is to follow your advice for the analysis variable (leaving blank or NA), but add a separate "why is it missing" indicator variable. The values for that variable help track whatever the causes of missing data might be, like 1 = equipment failure; 2 = participant refusal; 3 = examiner error; 4 = file lost; 5 = tears of research assistants blurred the numbers, etc. :) The frequencies of each error need to be reported in the methods section of any later publications. This method does have two main drawbacks: 1) it adds more variables to the dataset and 2) it adds an extra layer of data checking to make sure that each NA value in one column has a reason for it in the other column. This is likely why some folks go with the -999 route.

I know this particular lesson is geared towards ecology and the "why is it missing" problem may not be broadly applicable. I wasn't sure how else to contribute to the discussion, so I'm sorry for the Github issue- if there is a better way please let me know. Other folks in different fields may have different solutions- it would be great to share what works in some forum!

Thanks again for all the wonderful materials-
Alison Hill
hillali@ohsu.edu

**Comment by fmichonneau** [comment]
Hi Alison,

Thanks for your comments. Using GitHub works very well for this.

You rise some good points that I have been intending to add to these lessons. People use data in spreadsheets at multiple steps of the data life cycle, and the problem you describe results from this tension between what is convenient at the time of data entry, and what is best practice when preparing the data for analysis and long-term storage. I'm hoping to add this section to the lessons soon.

Thanks again!

**Comment by apreshill** [comment]
Thanks! But I would argue it is critical at all life stages in human subjects research, including analysis and long-term storage, since how many/why missing should always be reported in publications and therefore should be reproducible. Also, findings can't be interpreted without this info: i.e., 80% of kids were able to do some task, but 50% refused to do it. With larger datasets, analyzing why data is missing is a research question (were kids with more language problems more likely to refuse? did our pitch tracking software systematically produce more missing values for younger vs. older kids?). Anyway, thanks for the response!

**Comment by cbahlai** [comment]
I like this a lot, Alison- we see this sort of thing in ecology too- was the data missing, compromised, still being processed, etc- I think the key here is not to include some sort of conditional null, but to encode this data in another field. This limits the danger of assumptions being made (ie analyses accidentally done with a set of different nulls)- at least that's how I'd approach it with a dataset of messy ecological observations! My thinking is it's usually easier to collapse together information when needed than to tease it apart when a single observation could have multiple meanings. I think we should work a bit of this into the lesson, conceptually.

**Comment by ErinBecker** [comment]
@apreshill @fmichonneau @cbahlai - I really enjoyed the discussion here and agree that this would be a valuable addition to this lesson. Just by way of record-keeping, I'm adding an "after-lesson-release" tag here just to indicate that this won't be incorporated into the lesson before publication at the end of this month. If you're planning on finishing this before lesson release, please let me know and I'll remove the tag!

**Comment by tracykteal** [comment]
Thanks for this discussion. I agree with @cbahlai that encoding this information in a different column would be good practice and @apreshill your suggestion about the 'why is it missing' variable. It's a similar idea of 'using formatting to convey information' where the suggestion is to create a 'calibration' comment, rather than include that information with formatting.  

I added a section to the 'null values' section about reasons why null values might have been conveyed differently, and this suggestion about new columns in some cases in https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/232

**Comment by fmichonneau** [comment]
it seems that this issue was addressed in #232 so I'm close it. @apreshill if you think it is not the case, and this can be improved further, please feel free to reopen or create a new issue. Thanks!
