### ISSUE TITLE
add examples with gene names converted to dates

### ISSUE THREAD

**Issue by mkuzak** [datacarpentry/spreadsheet-ecology-lesson#5]
There was a paper and a blog post with examples with gene names that where similar to dates and have been converted by excel to dates.

https://nsaunders.wordpress.com/2012/10/22/gene-name-errors-and-excel-lessons-not-learned/

**Comment by plijnzaad** [comment]
A nice overview of some common pitfals of using Excel in bioinformatics can be found in [Mistaken Identifiers: Gene name errors can be introduced inadvertently when using Excel in bioinformatics. Zeeberg et al., BMC Bioinformatics 2004, 5:80 ](http://www.biomedcentral.com/1471-2105/5/80)

**Comment by tracykteal** [comment]
Thanks, these are good pointers. 

This issue might be good to move over to the organization-genomics lesson https://github.com/datacarpentry/organization-genomics

@mkuzak and @plijnzaad ok if we move it over there?

**Comment by ErinBecker** [comment]
Agreed that it would be good to move this to the genomics lessons as it seems more relevant there. @mkuzak and @plijnzaad would this be ok?

**Comment by mkuzak** [comment]
I think it's relevant to both. It's an example from genomics but deals with what not to do in the spreadsheet.

**Comment by ErinBecker** [comment]
Thanks @mkuzak. I think this is likely a change that won't happen before the release of this lesson at the end of the month. Just by way of record-keeping, I'm adding an "after-lesson-release" tag here. If you (or someone else) would like to incorporate this before lesson release, please let me know and I'll remove the tag!

**Comment by hoytpr** [comment]
@ErinBecker , I think @mkuzak is correct and this is relevant to both.  OMG I had fits working with all the Septins (SEP1-13) and Membrane Associated Receptors (MAR) of the dog genome.  The topic fits in well with the use of dates and proper formatting. It's also *important* because some of the changes Excel makes **cannot be changed back** to the original text!! I'm not saying I'll have time to write up a good exercise, but the sooner the better.

**Comment by fmichonneau** [comment]
It looks like this was addressed in #231, so I'm going to close this issue. @mkuzak if you think more details are needed, please feel free to reopen. Thanks!
