### ISSUE TITLE
04-quality-control anomalous spreadsheet tab reference

### ISSUE THREAD

**Issue by gallingerj** [datacarpentry/spreadsheet-ecology-lesson#52]
Under Quality Control > Sorting, a 1980 tab in the messy spreadsheet is referenced. This tab does not exist in the hyperlinked file on Figshare that is associated with the lesson. Is this reference a relic of a past version of the lesson?

**Comment by ctb** [comment]
Confirmed with @tracykteal - I ran into the same issue while preparing for a workshop today :). Tracy says she doesn't teach this lesson any more, so perhaps it should be removed; OR, some fake data created and added to the spreadsheet...?

**Comment by debpaul** [comment]
To show sort, I created a third sheet with all the data (not totally cleaned up), just copied and pasted to create. Then I used that to do sort, to show finding outliers and other issues.

**Comment by ctb** [comment]
yeah, that was my plan too :).

On Thu, Oct 20, 2016 at 07:22:59AM -0700, Debbie Paul wrote:
> To show sort, I created a third sheet with all the data (not totally cleaned up), just copied and pasted to create. Then I used that to do sort, to show finding outliers and other issues. 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/52#issuecomment-255120372
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by ErinBecker** [comment]
As far as I can tell, this lesson no longer references a "1980" tab, but it does have the line "Select the plot_id column" in the instructions for data validation. None of the three tabs have a "plot_id" column, but the 2013 tab has a "Plot" column (three of them actually). This should be updated to clearly indicate the tab that the learner should be looking at and change the variable name from "plot_id" to "Plot". Should we also tell the learner to apply this validation step to all three "Plot" columns?

**Comment by ErinBecker** [comment]
Fixed with https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/149
