### ISSUE TITLE
caveats of popular data formats file

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/spreadsheet-ecology-lesson#73]
The file 06-data-formats-caveats.md was originally a lesson, but most of its elements were integrated into other lessons. It is now in _extras/

It should be moved out of there, and perhaps the information put somewhere information put somewhere else. Perhaps some might be good for reference.md.

**Comment by ErinBecker** [comment]
related to https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/159

**Comment by ErinBecker** [comment]
Related to https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/95#issuecomment-287221567
