### ISSUE TITLE
What should we say about the data for this lesson?

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/spreadsheet-ecology-lesson#75]
In the Setup page, there is a short description of the dataset used here and in the rest of the ecology lesson. http://www.datacarpentry.org/spreadsheet-ecology-lesson/setup/

Is what is said here OK? 

Should we do a fuller description of the data, like here https://github.com/datacarpentry/ecology-workshop/blob/gh-pages/data.md and point to that description?

@ethanwhite

**Comment by ethanwhite** [comment]
I don't have any strong feelings on this. In general it seems like having it extensively introduced towards the beginning of the first day is the way to go.

**Comment by tracykteal** [comment]
Addressed in https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/182
