### ISSUE TITLE
authors and contributors

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/spreadsheet-ecology-lesson#76]
We have authors and contributors on each lesson. It's likely we should do something else with this information and follow what SWC does.

**Comment by ErinBecker** [comment]
@tracykteal - Let's leave the maintainers on the lesson files and remove the contributors list, since there are many more contributors now than are listed here. Sound ok?

**Comment by tracykteal** [comment]
Addressed in https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/175
