### ISSUE TITLE
Questions not questions

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/spreadsheet-ecology-lesson#77]
At the beginning of each lesson, there's a segment called 'Questions', but the sentences used there are statements rather than questions. Do we want to have statements rather than questions? These also go on the index page.

If we do want statements instead, we should update to something other than 'Questions'.

**Comment by benmarwick** [comment]
I edited these so that the questions are now 'Exercises', to emphasize the interactive nature of that part of the lesson (#137, #138, #139). Hope that's ok!

**Comment by ErinBecker** [comment]
Thanks @benmarwick. I think we also need to update the "questions" section in the YAML for each episode so that these are framed as questions. I'll take a stab at this next.

**Comment by ErinBecker** [comment]
Closed with #147
