### ISSUE TITLE
learning objectives stated twice

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/spreadsheet-ecology-lesson#78]
The Learning Objectives are stated twice - once in the box at the top and then immediately at the top of the lesson. 

I don't mind having them twice, but is this what we want to do?

Some potential options:
- change 'Objectives' in the top to 'Learning Objectives' and remove Learning Objectives at the top of the lesson
- keep them in both places
- change the 'Learning Objectives' section to something more casual. i.e. This lesson is about formatting data in spreadsheets. In this lesson you will learn ...

And I know there are a lot of other options.

**Comment by ashander** [comment]
I'd favor the first of your options. That way, there's only one location in the text to maintain. I also think they're pretty noticible/clear in the current layout

**Comment by ErinBecker** [comment]
Closed with #126
