### ISSUE TITLE
Install instructions for LibreOffice

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#87]
Inconsistent wording. 

The language for Windows and Linux is: "Once the installer is downloaded, double click on it and LibreOffice should install."

But for Mac OS X it is: "Once the installer is downloaded, double click on this file, and LibreOffice will be installed."

**Comment by anelda** [comment]
Fixed in https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/140
