### ISSUE TITLE
Code of conduct link isn't to shared DC/SWC code of conduct

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#93]
This is probably also the case for other lessons. The link to code of conduct at the top of the rendered lesson page (http://www.datacarpentry.org/spreadsheet-ecology-lesson/conduct/) should go back to the official DC/SWC code of conduct (http://www.datacarpentry.org/code-of-conduct/) or the language from this CoC that is specific to project contribution should be incorporated into our official CoC. We shouldn't have two different CoCs. @pbarmby as head of Policy subcommittee.

**Comment by tracykteal** [comment]
Related to https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/71

**Comment by PBarmby** [comment]
I can deal with this sometime in the next week or so. If someone wants to assign it to me (or make me a datacarpentry member and I'll assign it to myself!) that's fine.

**Comment by ErinBecker** [comment]
Thanks @PBarmby, I just added you to the organization.
