### ISSUE TITLE
Extras/reference or glossary?

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#94]
The page that appears from selecting Extras/reference is titled "Glossary" and appears to be a compendium of the key points from each lesson. Do these key points auto-update if they are changed in the lesson files? Or is this where they should be changed?

- Make name consistent (reference or glossary)
- Fix "FIXME" at bottom of page.

**Comment by tracykteal** [comment]
Related to https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/72
