### ISSUE TITLE
05-data-formats-caveats doesn't have correct style

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#95]
It looks like http://www.datacarpentry.org/spreadsheet-ecology-lesson/extras/06-data-formats-caveats.html doesn't have the new template implemented. There are also problems with broken markdown (### that doesn't render as headers), and empty sections ("Tab Separated Values" format and "Other delimiters for data formats" are both empty).

If this is meant to be a usable extension to the lesson it should be formatted and added to the index page as an optional module.

**Comment by tracykteal** [comment]
Related to https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/73

**Comment by ErinBecker** [comment]
@tracykteal I think the best solution here is to remove the data-formats-caveats module from the lesson release and incorporate these changes for the next version. Does this sound like an ok solution for now?

**Comment by tracykteal** [comment]
I agree that not having it not be an episode sounds good. What about putting it in discussion.md? That seems to be the general sort of thing in the SWC discussion.md files. After release, we could potentially cut it down a little, even in the discussion section.

**Comment by tracykteal** [comment]
Then there could be a link when we're talking about exporting as csv and say "For more of a discussion on data formats see the discussion page"

**Comment by tracykteal** [comment]
Addressed by https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/172
