### ISSUE TITLE
Maybe we should change the word willy-nilly

### ISSUE THREAD

**Issue by arborgirl** [datacarpentry/spreadsheet-ecology-lesson#98]
In exporting data, the word willy-nilly is used. Maybe we should change it. Maybe not everyone knows or uses it.

**Comment by ErinBecker** [comment]
Thanks @arborgirl, that's a really good point given that our lessons are used in many different countries and willy-nilly is probably an American phrase.

**Comment by ErinBecker** [comment]
Closed with #130
