### ISSUE TITLE
The part that has /r/n is a little bit confusing. Maybe we should change it.

### ISSUE THREAD

**Issue by arborgirl** [datacarpentry/spreadsheet-ecology-lesson#99]
The part in A Note on Cross-platform Operability that has /r/n in it and it is a bit confusing. Maybe we could change it so it is less confusing.

**Comment by ErinBecker** [comment]
Thanks @arborgirl!

**Comment by ErinBecker** [comment]
I agree with @arborgirl that this section seems much more advanced than the rest of this lesson. Learners are unlikely to be familiar with the concepts of:
- UNIX-style (vs other) encoding systems
- line breaks being represented with text characters (if they've mostly worked with rich text editors)
- version control (this also has shaming language "which you should be doing!")
- config files

This section also introduces a lot of new vocabulary without explaining these new terms (eg. packages, environments, dependencies). 

Can this section be moved to _extras? Or is it really something that novices need to know?

**Comment by zjsteyn** [comment]
I agree as well, I also experienced it as additional cognitive load late in the lesson and it can cause a coherent lesson to "collapse" a bit if you end on a technical note.

One possibility is to maybe move it as you suggested to _extras, or rather generate a table that shows the grid for data1 and data2 and show what may happen if it does not parce correctly in grid format. That being said, I have not tried to replicate the error in practice, but in theory it should play out like this?

**For example:**

Show data1 data2 grid:
<img width="307" alt="screen shot 2017-03-31 at 7 15 07 pm" src="https://cloud.githubusercontent.com/assets/13110354/24560663/db4a5786-1643-11e7-931a-ca2c72336878.png">

Exporting to CSV, the text wil look like this:
data1,data2\r\n1,2\r\n4,5\r\n

But if you import it into a system that does not parse the "\r" it will interpret the differently:
data1
data2\r
1
2\r
…

Which genereates the following grid:

<img width="308" alt="screen shot 2017-03-31 at 7 26 42 pm" src="https://cloud.githubusercontent.com/assets/13110354/24561066/a990327c-1645-11e7-90b5-35a44e90f8d9.png">

This may be easier to interpret than the text based / non grid exaples of line endings.

**Comment by ErinBecker** [comment]
@zjsteyn Thank you for the detailed example. I think that these graphics and explanation would really help clarify this section of the lesson. Would you be able to put together a pull request for incorporating these changes?

**Comment by zjsteyn** [comment]
Will do!

**Comment by ErinBecker** [comment]
@zjsteyn Awesome, thanks!

**Comment by zjsteyn** [comment]
Pull request created.

**Comment by ErinBecker** [comment]
Great, thanks @zjsteyn! I'll take a look at this today.
